pipeline {
    agent none
    stages {
        stage('Back-end') {
            agent {
                docker { image 'maven:3.8.1-adoptopenjdk-11' }
            }
            steps {
                // Clone the repository
                git 'https://github.com/dmolio/Jenkins-Zero-To-Hero.git'
                
                // Change the current directory to 'multi-stage-test/backend'
                dir('multi-stage-test/backend') {
                    // Build the application and run tests
                    sh 'mvn clean install'
                }
            }
        }
        stage('Front-end') {
            agent {
                docker { image 'node:16-alpine' }
            }
            steps {
                // Use the same repository, already cloned
                dir('multi-stage-test/frontend') {
                    // Install dependencies
                    sh 'npm install'
                    
                    // Run tests
                    sh 'npm test'
                }
            }
        }
    }
}